
server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: where0502
    driver-class-name: org.postgresql.Driver
  jackson:
    mapper:
      accept-case-insensitive-enums: true
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

